
controller:
  replicaCount: 1     
  image:             
    repository: dutt1/mt1
    tag: 1
    pullPolicy: IfNotPresent

replicaCount: 1        
image:
  repository: dutt1/bg1
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1"   

